# Generated by Django 4.2.17 on 2025-01-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director2',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите второго режиссера'),
        ),
    ]
