# Generated by Django 4.2.17 on 2025-01-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_movies_director2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director2',
        ),
    ]
