# Generated by Django 4.2.17 on 2025-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0004_alter_movies_options_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movies', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=100, verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre_choices',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Romance', 'Romance')], max_length=100, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(upload_to='movies/', verbose_name='load photo'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.PositiveIntegerField(default=400, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='time_watch',
            field=models.PositiveIntegerField(default=120, verbose_name='duartion'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name of the movie'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer',
            field=models.URLField(verbose_name='YouTube trailer'),
        ),
    ]
