# Generated by Django 4.2.17 on 2025-01-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tv_show', '0004_alter_movies_options_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('checked', models.CharField(choices=[('✅', '✅'), ('❌', '❌')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('choice_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_show.movies')),
            ],
        ),
    ]
